### ISSUE TITLE
devtools support for non-poetry components - ci commands

### ISSUE THREAD

**Issue by elonp** [microsoft/rats#342]
Currently devtools ci commands are prefixed with "poetry run".
This needs to not happen when they are overridden using `ci.PluginServices.CONFIGS.COMMAND_GROUPS`, but we need to find some other way to specify the virtual environment to use.

**Comment by ms-lolo** [comment]
after updating the `ProjectTools` and `ComponentTools` to be less poetry-specific, i deleted any remaining ci command that wasn't trivial to support. since they were all just shortcuts to poetry commands, you should be able to go back to using your favorite package tool directly and not worry about doing it through `rats-devtools ci` subcommands.

`rats-devtools` should work with `pdm`, `uv`, and `poetry` now with a few new tests but it should also work with any other `PEP 621` compatible tool (still can't support conda).
